version: '3.4'

services:
  

  webapi:
    build:
      context: .
      dockerfile: FPTShareLaptop_Controller/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - sqlserver
    networks:
      - fptnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnectionString=Server=FPTShareLaptopSP.mssql.somee.com;Database=FPTShareLaptopSP;User Id=phudmse161044_SQLLogin_1;Password=lowlzu76pd;TrustServerCertificate=True;MultipleActiveResultSets=true;
      - OPENAI_API_KEY=${OPENAI_API_KEY}

networks:
  fptnet:
    driver: bridge